# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/LUT/LUT.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# XDC: c:/Users/Wiktor/Downloads/SR_projects/simulation_models/simulation_models.gen/sources_1/ip/LUT/LUT_ooc.xdc
